Q1

In [ ]:
import pandas as pd
import numpy as np

fixed_entries = [
    {"question": "what is the annual fee",
     "answer": "The annual fee is Rs 500.",
     "keywords": "fee cost price charge",
     "category": "billing"},
    {"question": "how to reset password",
     "answer": "Go to Settings > Reset Password.",
     "keywords": "password reset login",
     "category": "account"},
    {"question": "what are your working hours",
     "answer": "We are open 9 AM to 5 PM.",
     "keywords": "hours timing open time",
     "category": "general"},
    {"question": "how can i pay the fee",
     "answer": "You can pay via UPI, card, or net banking.",
     "keywords": "pay payment upi fee",
     "category": "billing"},
]

roll = 1024170305
d = [int(digit) for digit in str(roll)[-2:]]
cat = ["billing", "account", "general"]
cat_main = []
for i in d:
    cat_main.append(cat[i % 3])
questions = [
    "how do i check my payment status",
    "how can i contact support"
]
answers = [
    "You can check your payment status in the Payments section of your account.",
    "You can contact support through the Help Center or email us."
]
keywords = [
    "payment status billing transaction",
    "support help contact"
]
newFqa = []
for i in range(2):
    newFqa.append({
        "question": questions[i],
        "answer": answers[i],
        "keywords": keywords[i],
        "category": cat_main[i]
    })
newFqa.extend(fixed_entries)


df = pd.DataFrame(newFqa)


print(df)

                           question  \
0  how do i check my payment status
1         how can i contact support
2            what is the annual fee
3             how to reset password
4       what are your working hours
5             how can i pay the fee

                                              answer  \
0  You can check your payment status in the Payme...
1  You can contact support through the Help Cente...
2                          The annual fee is Rs 500.
3                   Go to Settings > Reset Password.
4                          We are open 9 AM to 5 PM.
5         You can pay via UPI, card, or net banking.

                             keywords category
0  payment status billing transaction  billing
1                support help contact  general
2               fee cost price charge  billing
3                password reset login  account
4              hours timing open time  general
5                 pay payment upi fee  billing

In [ ]:
df = pd.DataFrame(newFqa)
df

,question,answer,keywords,category
0,how do i check my payment status,You can check your payment status in the Payme...,payment status billing transaction,billing
1,how can i contact support,You can contact support through the Help Cente...,support help contact,general
2,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
3,how to reset password,Go to Settings > Reset Password.,password reset login,account
4,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
5,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

Q2

In [ ]:
def scoring(query,df):
  questions = [sent.lower().split() for sent in df['question']]
  actual = query.lower().split()
  order = []
  for i in range(len(questions)):
    cnt = 0
    for w in actual:
      if(w in questions[i]):
        cnt+=1
    order.append(cnt)
  sorted_order = np.argsort(order)
  ans =[]
  for i in range(len(order)):
    ans.append(df['question'][sorted_order[i]])
  return ans

In [ ]:
print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
Here are FAQ's in sorted order -> (increasing order of matching)
['how can i contact support', 'how to reset password', 'what are your working hours', 'how do i check my payment status', 'what is the annual fee', 'how can i pay the fee']

Q3

In [ ]:
def same_category(category_name,df):
    l = df.groupby('category')['question'].apply(list)
    return l[category_name]

In [ ]:
print(same_category(cat_main[0],df))

['how do i check my payment status', 'what is the annual fee', 'how can i pay the fee']

Q4

In [ ]:
key = input("Please Enter new Keyword for question 1 : ")
df.loc[0,'keywords']+=" " + key.lower()
df.to_csv('1024170305_faq_data.csv', index=False)

In [ ]:
df_new = pd.read_csv('1024170305_faq_data.csv');
df_new

,question,answer,keywords,category
0,how do i check my payment status,You can check your payment status in the Payme...,payment status billing transaction fast,billing
1,how can i contact support,You can contact support through the Help Cente...,support help contact,general
2,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
3,how to reset password,Go to Settings > Reset Password.,password reset login,account
4,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
5,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

Q5

In [ ]:
print(df.groupby('category')['question'].count())

category
account    1
billing    3
general    2
Name: question, dtype: int64

Q6

In [ ]:
def scoring(query,df):
  questions = [sent.lower().split() for sent in df['question']]
  actual = query.lower().split()
  order = []
  for i in range(len(questions)):
    cnt = 0
    for w in actual:
      if(w in questions[i]):
        cnt+=1
    order.append(cnt)
  ans ={}
  for i in range(len(order)):
        if order[i] not in ans:
            ans[order[i]] = []

        ans[order[i]].append(df['question'][i])
  max_score = max(order)
  print("Highest score:", max_score)
  print("Matching questions:")
  for question in ans[max_score]:
      print(question)

  return ans

In [ ]:
print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
Highest score: 1
Matching questions:
how to reset password
Here are FAQ's in sorted order -> (increasing order of matching)
{0: ['how do i check my payment status', 'how can i contact support', 'what is the annual fee', 'what are your working hours', 'how can i pay the fee'], 1: ['how to reset password']}

In [ ]:
print("Please enter a query")
query = input()
ranked_FAQ = scoring(query,df)
print("Here are FAQ's in sorted order -> (increasing order of matching)")
print(ranked_FAQ)

Please enter a query
Highest score: 1
Matching questions:
what are your working hours
Here are FAQ's in sorted order -> (increasing order of matching)
{0: ['how do i check my payment status', 'how can i contact support', 'what is the annual fee', 'how to reset password', 'how can i pay the fee'], 1: ['what are your working hours']}